---
- name: Install Forgejo
  hosts: util-sparkle
  become: yes  # To execute tasks with sudo privileges

  tasks:
    - name: Download binary
      get_url:
        url: "https://codeberg.org/forgejo/forgejo/releases/download/v7.0.0/forgejo-7.0.0-linux-amd64"  # Replace with your binary URL
        dest: "/tmp/forgejo"  # Destination path to download the binary

    - name: Ensure /usr/local/bin directory exists
      file:
        path: "/usr/local/bin"
        state: directory

    - name: Set perms on exec
      shell: 
        cmd: chmod +x /tmp/forgejo
        warn: false

    - name: Install binary
      shell: mv /tmp/forgejo /usr/local/bin/forgejo

    - name: Install EPEL
      shell: 
        cmd: yum install -y epel-release && yum update && yum repolist
        warn: false

    - name: Install IUS.io
      shell:
        warn: false
        cmd: yum install https://repo.ius.io/ius-release-el7.rpm https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && yum update && yum repolist

    - name: Ensure git and git-lfs are installed
      package:
        name:
          - git236
          - git-lfs
        state: present

    - name: Create git user on Debian or Ubuntu
      when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
      user:
        name: git
        comment: 'Git Version Control'
        shell: /bin/bash
        home: /home/git
        system: yes
        group: git
        createhome: yes
        state: present

    - name: Create git user on RedHat-esque distributions
      when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat" or ansible_distribution == "AlmaLinux" or ansible_distribution == "Rocky Linux"
      group:
        name: git
        state: present
      tags:
        - git_group

    - name: Ensure git user exists
      user:
        name: git
        comment: 'Git Version Control'
        shell: /bin/bash
        home: /home/git
        system: yes
        group: git
        createhome: yes
        state: present
      tags:
        - git_user

    - name: Misc Tasks to Prep /var/lib for Forgejo
      shell: mkdir /var/lib/forgejo ; chown git:git /var/lib/forgejo && chmod 750 /var/lib/forgejo

    - name: Misc Tasks to Prep /etc/forgejo
      shell: mkdir /etc/forgejo ; chown root:git /etc/forgejo && chmod 770 /etc/forgejo

    - name: Get and install SystemD unit file
      shell: wget -O /etc/systemd/system/forgejo.service https://codeberg.org/forgejo/forgejo/raw/branch/forgejo/contrib/systemd/forgejo.service

    - name: Enable & Start SystemD unit
      shell: systemctl daemon-reload && systemctl enable --now forgejo

    - name: Install Nginx
      package:
        name: nginx
        state: present

    - name: Configure Nginx as a reverse proxy
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/conf.d/forgejo.conf

    - name: Ensure Nginx service is enabled and started
      shell:
        warn: false
        cmd: systemctl enable --now nginx

    - name: Restart nginx for shits n giggles
      shell:
        warn: false
        cmd: systemctl restart nginx

    - name: Open port 80 through Firewalld
      shell:
        warn: false
        cmd: firewall-cmd --permanent --add-port=80/tcp && firewall-cmd --reload