---
- name: Install Forgejo
  hosts: util-sparkle
  become: yes  # To execute tasks with sudo privileges

  tasks:
    - name: Download binary
      get_url:
        url: "https://codeberg.org/forgejo/forgejo/releases/download/v7.0.0/forgejo-7.0.0-linux-amd64" 
        dest: "/tmp/forgejo"

    - name: Ensure /usr/local/bin directory exists
      file:
        path: "/usr/local/bin"
        state: directory

    - name: Set perms on exec
      shell: 
        cmd: chmod +x /tmp/forgejo
        warn: false

    - name: Install binary
      shell: mv /tmp/forgejo /usr/local/bin/forgejo

    - name: Install EPEL
      shell: 
        cmd: yum install -y epel-release && yum update && yum repolist
        warn: false

    - name: Install ius-release if not installed
      command: yum list installed | grep -q ius-release
      register: ius_release_installed
      changed_when: false
      ignore_errors: true

    - name: Install ius.io
      shell:
        warn: false
        cmd: yum install -y https://repo.ius.io/ius-release-el7.rpm && yum update && yum repolist
      when: ius_release_installed.rc != 0

    - name: Ensure git and git-lfs are installed
      package:
        name:
          - git236
          - git-lfs
        state: present

    - name: Create git user on Debian or Ubuntu
      when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
      user:
        name: git
        comment: 'Git Version Control'
        shell: /bin/bash
        home: /home/git
        system: yes
        group: git
        createhome: yes
        state: present

    - name: Create git user on RedHat-esque distributions
      when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat" or ansible_distribution == "AlmaLinux" or ansible_distribution == "Rocky Linux"
      group:
        name: git
        state: present
      tags:
        - git_group

    - name: Ensure git user exists
      user:
        name: git
        comment: 'Git Version Control'
        shell: /bin/bash
        home: /home/git
        system: yes
        group: git
        createhome: yes
        state: present
      tags:
        - git_user

    - name: Misc Tasks to Prep /var/lib for Forgejo
      shell: mkdir /var/lib/forgejo ; chown git:git /var/lib/forgejo && chmod 750 /var/lib/forgejo

    - name: Misc Tasks to Prep /etc/forgejo
      shell: mkdir /etc/forgejo ; chown root:git /etc/forgejo && chmod 770 /etc/forgejo

    - name: Get and install SystemD unit file
      shell: wget -O /etc/systemd/system/forgejo.service https://codeberg.org/forgejo/forgejo/raw/branch/forgejo/contrib/systemd/forgejo.service

    - name: Enable & Start SystemD unit
      shell: systemctl daemon-reload && systemctl enable --now forgejo

    - name: Open port 3000 through Firewalld
      shell:
        warn: false
        cmd: firewall-cmd --permanent --add-port=3000/tcp && firewall-cmd --reload
