---
- name: Create a Linux Local User
  hosts: linux
  become: yes
  tasks:
  - name: Add user sparkle-gremlin
    user:
      name: sparkle-gremlin
      password: "{{ 'password' | password_hash('sha512') }}"
      shell: /bin/bash
      home: /home/sparkle-gremlin
